[workspace]
channels = ["conda-forge", "bioconda"]
name = "Stanford3Dfolding_dataprocessing"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.0.1,<8"
pandas = ">=2.3.3,<3"
mmseqs2 = ">=18.8cc5c,<19"
biopython = ">=1.85,<2"
tqdm = ">=4.67.1,<5"
retryhttp = ">=1.3.3,<2"
yaml = ">=0.2.5,<0.3"
duckdb = ">=1.4.3,<2"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
plotly = ">=6.4.0,<7"
nbformat = ">=5.10.4,<6"
line_profiler = ">=5.0.0,<6"
dask = ">=2025.11.0,<2026"
scalene = ">=1.5.51,<2"
usalign = ">=20241201,<20241202"
duckdb-cli = ">=1.4.3,<2"
fsspec = ">=2025.12.0,<2026"

[environments]
dev = []

[pypi-dependencies]
ipymolstar = ">=0.1.0, <0.2"
biotite = "==1.5.0"
